# Generated by Django 6.0.4 on 2026-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_herosection_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=10, verbose_name='Ombordagi soni'),
        ),
    ]
