# Generated by Django 6.0.4 on 2026-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='image_scale',
            field=models.IntegerField(default=100, verbose_name='Rasm masshtabi (%)'),
        ),
    ]
